### ISSUE TITLE
CS201912131_117 (Exc L5-6 FEZF2 LPO) is under oligo-opc

### ISSUE THREAD

**Issue by shawntanzk** [AllenInstitute/MOp_taxonomies_ontology#17]
Currently CS201912131_117 (Exc L5-6 FEZF2 LPO) is under oligo-opc,
it is also under (Mouse L5/6 NP)-like and (Mouse Non-IT projecting)-like and glutamatergic (these are correct I assume)
Should this be removed from oligo-opc? 

cell_set_preferred_alias | cell_set_label | cell_set_accession | cell_set_aligned_alias | cell_set_alias_assignee | cell_set_alias_citation | cell_set_structure | cell_set_ontology_tag | species | modality | taxonomy_id | taxonomy_description | child_cell_set_accessions | cell_type_card | original_label | cell_set_color
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- 
Exc L5-6 FEZF2 LPO | RNAseq 116 | CS201912131_117 |   | Nikolas Jorstad | PMID:34616062 | primary motor cortex | UBERON:0001384 | Human | RNAseq | CCN201912131 | Human M1   transcriptomics taxonomy | Cell Type | Exc L5-6 FEZF2 LPO 
Oligo-OPC | RNAseq 116-120 | CS201912131_147 | Oligodendrocyte-OPC | Nikolas Jorstad | PMID:34616062 | primary motor cortex | UBERON:0001384 | Human | RNAseq | CCN201912131 | Human M1 transcriptomics taxonomy | CS201912131_79\|CS201912131_117\|CS201912131_118\|CS201912131_119\|CS201912131_120 | No |   | #598077

**Comment by raymond-sanchez** [comment]
I'll double check with Jeremy that there's not a good reason it's like this (I think he uploaded this file), but I'd say it's fine to remove RNAseq 116 from Oligo-OPC, yes. Guessing that's either an error or something leftover from an earlier version of the taxonomy
